// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <nlohmann/json.hpp>
#include <stdexcept>
#include <string_view>

namespace company::model {

inline const char* cjm_to_json_string(Status value) {
    switch (value) {
    case Status::Active:
        return "Active";
    case Status::Disabled:
        return "Disabled";
    }
    throw std::invalid_argument("unknown enum value for company::model::Status");
}

inline Status cjm_from_json_string_Status(std::string_view value) {
    if (value == "Active") {
        return Status::Active;
    }
    if (value == "Disabled") {
        return Status::Disabled;
    }
    throw std::invalid_argument("unknown enum string for company::model::Status");
}

} // namespace company::model

namespace company::model {

inline void to_json(nlohmann::json& j, const Address& value) {
    j["city"] = value.city;
}

inline void from_json(const nlohmann::json& j, Address& value) {
    j.at("city").get_to(value.city);
}

} // namespace company::model

namespace company::model {

inline void to_json(nlohmann::json& j, const User& value) {
    j["name"] = value.name;
    j["age"] = value.age;
    j["tags"] = value.tags;
    j["address"] = value.address;
    j["status"] = value.status;
    if (value.nickname.has_value()) {
        j["nickname"] = *value.nickname;
    }
    if (value.score.has_value()) {
        j["score"] = *value.score;
    }
    j["samples"] = value.samples;
}

inline void from_json(const nlohmann::json& j, User& value) {
    j.at("name").get_to(value.name);
    j.at("age").get_to(value.age);
    j.at("tags").get_to(value.tags);
    j.at("address").get_to(value.address);
    j.at("status").get_to(value.status);
    if (j.contains("nickname")) {
        value.nickname = j.at("nickname").get<std::string>();
    }
    if (j.contains("score")) {
        value.score = j.at("score").get<int>();
    }
    j.at("samples").get_to(value.samples);
}

} // namespace company::model
