// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <nlohmann/json.hpp>

namespace company::model {

inline void to_json(nlohmann::json& j, const User& value) {
    j["name"] = value.name;
    j["age"] = value.age;
    if (value.nickname.has_value()) {
        j["nickname"] = *value.nickname;
    }
    if (value.score.has_value()) {
        j["score"] = *value.score;
    }
}

inline void from_json(const nlohmann::json& j, User& value) {
    j.at("name").get_to(value.name);
    j.at("age").get_to(value.age);
    if (j.contains("nickname")) {
        value.nickname = j.at("nickname").get<std::string>();
    }
    if (j.contains("score")) {
        value.score = j.at("score").get<int>();
    }
}

} // namespace company::model
