// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <cjm/model_contract.hpp>

namespace cjm::contract::generated_company_model_Address {

inline constexpr cjm::contract::type_descriptor city_type{
    cjm::contract::type_kind::string,
    "std::string",
    "std::string",
    nullptr,
    0,
};

inline constexpr cjm::contract::field_descriptor fields[] = {
    {
        "city",
        "city",
        false,
        false,
        {"include/address.hpp", 2, 17},
        &city_type,
    },
};

} // namespace cjm::contract::generated_company_model_Address

namespace cjm::contract::generated_company_model_User {

inline constexpr cjm::contract::type_descriptor name_type{
    cjm::contract::type_kind::string,
    "std::string",
    "std::string",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor age_type{
    cjm::contract::type_kind::signed_integer,
    "int",
    "int",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor tags_type{
    cjm::contract::type_kind::vector,
    "std::vector<std::string>",
    "std::vector<std::string>",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor address_type{
    cjm::contract::type_kind::object,
    "company::model::Address",
    "company::model::Address",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor status_type{
    cjm::contract::type_kind::enum_,
    "company::model::Status",
    "company::model::Status",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor nickname_type{
    cjm::contract::type_kind::optional,
    "std::optional<std::string>",
    "std::optional<std::string>",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor score_type{
    cjm::contract::type_kind::optional,
    "std::optional<int>",
    "std::optional<int>",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor internal_id_type{
    cjm::contract::type_kind::signed_integer,
    "int",
    "int",
    nullptr,
    0,
};

inline constexpr cjm::contract::field_descriptor fields[] = {
    {
        "name",
        "name",
        false,
        false,
        {"include/user.hpp", 2, 27},
        &name_type,
    },
    {
        "age",
        "age",
        false,
        false,
        {"include/user.hpp", 3, 9},
        &age_type,
    },
    {
        "tags",
        "tags",
        false,
        false,
        {"include/user.hpp", 6, 37},
        &tags_type,
    },
    {
        "address",
        "address",
        false,
        false,
        {"include/user.hpp", 7, 13},
        &address_type,
    },
    {
        "status",
        "status",
        false,
        false,
        {"include/user.hpp", 8, 12},
        &status_type,
    },
    {
        "nickname",
        "nickname",
        false,
        true,
        {"include/user.hpp", 4, 39},
        &nickname_type,
    },
    {
        "score",
        "score",
        false,
        true,
        {"include/user.hpp", 5, 28},
        &score_type,
    },
    {
        "internal_id",
        "",
        true,
        false,
        {"include/user.hpp", 9, 9},
        &internal_id_type,
    },
};

} // namespace cjm::contract::generated_company_model_User
