// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <nlohmann/json.hpp>
#include <cjm/model_contract.hpp>

namespace company::model {

inline void to_json(nlohmann::json& j, const Address& value) {
    j["city"] = value.city;
}

inline void from_json(const nlohmann::json& j, Address& value) {
    j.at("city").get_to(value.city);
}

} // namespace company::model

namespace cjm::contract::generated_company_model_Address {

inline constexpr cjm::contract::type_descriptor city_type{
    cjm::contract::type_kind::string,
    "std::string",
    "std::string",
    nullptr,
    0,
};

} // namespace cjm::contract::generated_company_model_Address

namespace company::model {

inline void to_json(nlohmann::json& j, const User& value) {
    j["name"] = value.name;
    j["age"] = value.age;
    j["tags"] = value.tags;
    j["address"] = value.address;
    j["status"] = value.status;
    if (value.nickname.has_value()) {
        j["nickname"] = *value.nickname;
    }
    if (value.score.has_value()) {
        j["score"] = *value.score;
    }
}

inline void from_json(const nlohmann::json& j, User& value) {
    j.at("name").get_to(value.name);
    j.at("age").get_to(value.age);
    j.at("tags").get_to(value.tags);
    j.at("address").get_to(value.address);
    j.at("status").get_to(value.status);
    if (j.contains("nickname")) {
        value.nickname = j.at("nickname").get<std::string>();
    }
    if (j.contains("score")) {
        value.score = j.at("score").get<int>();
    }
}

} // namespace company::model

namespace cjm::contract::generated_company_model_User {

inline constexpr cjm::contract::type_descriptor name_type{
    cjm::contract::type_kind::string,
    "std::string",
    "std::string",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor age_type{
    cjm::contract::type_kind::signed_integer,
    "int",
    "int",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor tags_type{
    cjm::contract::type_kind::vector,
    "std::vector<std::string>",
    "std::vector<std::string>",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor address_type{
    cjm::contract::type_kind::object,
    "company::model::Address",
    "company::model::Address",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor status_type{
    cjm::contract::type_kind::enum_,
    "company::model::Status",
    "company::model::Status",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor nickname_type{
    cjm::contract::type_kind::optional,
    "std::optional<std::string>",
    "std::optional<std::string>",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor score_type{
    cjm::contract::type_kind::optional,
    "std::optional<int>",
    "std::optional<int>",
    nullptr,
    0,
};

} // namespace cjm::contract::generated_company_model_User
