// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <nlohmann/json.hpp>

namespace company::model {

inline void to_json(nlohmann::json& j, const Address& value) {
    j["city"] = value.city;
}

inline void from_json(const nlohmann::json& j, Address& value) {
    j.at("city").get_to(value.city);
}

} // namespace company::model

namespace company::model {

inline void to_json(nlohmann::json& j, const User& value) {
    j["name"] = value.name;
    j["address"] = value.address;
}

inline void from_json(const nlohmann::json& j, User& value) {
    j.at("name").get_to(value.name);
    j.at("address").get_to(value.address);
}

} // namespace company::model
