// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <nlohmann/json.hpp>
#include <cjm/model_contract.hpp>

namespace company::model {

inline void to_json(nlohmann::json& j, const Address& value) {
    j["city"] = value.city;
}

inline void from_json(const nlohmann::json& j, Address& value) {
    j.at("city").get_to(value.city);
}

} // namespace company::model

namespace cjm::contract::generated_company_model_Address {

inline constexpr cjm::contract::type_descriptor city_type{
    cjm::contract::type_kind::string,
    "std::string",
    "std::string",
    nullptr,
    0,
};

} // namespace cjm::contract::generated_company_model_Address

namespace company::model {

inline void to_json(nlohmann::json& j, const User& value) {
    j["name"] = value.name;
    j["address"] = value.address;
}

inline void from_json(const nlohmann::json& j, User& value) {
    j.at("name").get_to(value.name);
    j.at("address").get_to(value.address);
}

} // namespace company::model

namespace cjm::contract::generated_company_model_User {

inline constexpr cjm::contract::type_descriptor name_type{
    cjm::contract::type_kind::string,
    "std::string",
    "std::string",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor address_type{
    cjm::contract::type_kind::object,
    "company::model::Address",
    "company::model::Address",
    nullptr,
    0,
};

} // namespace cjm::contract::generated_company_model_User
