// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <nlohmann/json.hpp>

namespace company::model {

inline void to_json(nlohmann::json& j, const User& value) {
    j["labels"] = value.labels;
    j["aliases"] = value.aliases;
    if (value.optional_labels.has_value()) {
        j["optional_labels"] = *value.optional_labels;
    }
    if (value.optional_aliases.has_value()) {
        j["optional_aliases"] = *value.optional_aliases;
    }
}

inline void from_json(const nlohmann::json& j, User& value) {
    j.at("labels").get_to(value.labels);
    j.at("aliases").get_to(value.aliases);
    if (j.contains("optional_labels")) {
        value.optional_labels = j.at("optional_labels").get<std::map<std::string, int>>();
    }
    if (j.contains("optional_aliases")) {
        value.optional_aliases = j.at("optional_aliases").get<std::unordered_map<std::string, std::string>>();
    }
}

} // namespace company::model
