// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <nlohmann/json.hpp>
#include <cjm/model_contract.hpp>

namespace company::model {

inline void to_json(nlohmann::json& j, const User& value) {
    j["labels"] = value.labels;
    j["aliases"] = value.aliases;
    if (value.optional_labels.has_value()) {
        j["optional_labels"] = *value.optional_labels;
    }
    if (value.optional_aliases.has_value()) {
        j["optional_aliases"] = *value.optional_aliases;
    }
}

inline void from_json(const nlohmann::json& j, User& value) {
    j.at("labels").get_to(value.labels);
    j.at("aliases").get_to(value.aliases);
    if (j.contains("optional_labels")) {
        value.optional_labels = j.at("optional_labels").get<std::map<std::string, int>>();
    }
    if (j.contains("optional_aliases")) {
        value.optional_aliases = j.at("optional_aliases").get<std::unordered_map<std::string, std::string>>();
    }
}

} // namespace company::model

namespace cjm::contract::generated_company_model_User {

inline constexpr cjm::contract::type_descriptor labels_type{
    cjm::contract::type_kind::map,
    "std::map<std::string, int>",
    "std::map<std::string, int>",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor aliases_type{
    cjm::contract::type_kind::map,
    "std::unordered_map<std::string, std::string>",
    "std::unordered_map<std::string, std::string>",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor optional_labels_type{
    cjm::contract::type_kind::optional,
    "std::optional<std::map<std::string, int>>",
    "std::optional<std::map<std::string, int>>",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor optional_aliases_type{
    cjm::contract::type_kind::optional,
    "std::optional<std::unordered_map<std::string, std::string>>",
    "std::optional<std::unordered_map<std::string, std::string>>",
    nullptr,
    0,
};

} // namespace cjm::contract::generated_company_model_User
