// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <cjm/model_contract.hpp>

namespace cjm::contract::generated_company_contract_test_RecursiveAddress {

inline constexpr cjm::contract::type_descriptor city_type{
    cjm::contract::type_kind::string,
    "std::string",
    "std::string",
    nullptr,
    0,
    nullptr,
    0,
};

inline constexpr cjm::contract::field_descriptor fields[] = {
    {
        "city",
        "city",
        false,
        false,
        {"include/recursive_contract.hpp", 11, 17},
        &city_type,
    },
};

} // namespace cjm::contract::generated_company_contract_test_RecursiveAddress

template <>
struct cjm::contract::model_traits<company::contract_test::RecursiveAddress> {
    static constexpr cjm::contract::model_descriptor model{
        "RecursiveAddress",
        "company::contract_test::RecursiveAddress",
        {"include/recursive_contract.hpp", 10, 8},
        cjm::contract::generated_company_contract_test_RecursiveAddress::fields,
        1,
    };
};

namespace cjm::contract::generated_company_contract_test_RecursiveContract {

inline constexpr cjm::contract::type_descriptor matrix_type_arg0_arg0{
    cjm::contract::type_kind::signed_integer,
    "int",
    "int",
    nullptr,
    0,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor matrix_type_arg0_arguments[] = {
    matrix_type_arg0_arg0,
};

inline constexpr cjm::contract::type_descriptor matrix_type_arg0{
    cjm::contract::type_kind::vector,
    "std::vector<int>",
    "std::vector<int>",
    matrix_type_arg0_arguments,
    1,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor matrix_type_arguments[] = {
    matrix_type_arg0,
};

inline constexpr cjm::contract::type_descriptor matrix_type{
    cjm::contract::type_kind::vector,
    "std::vector<std::vector<int>>",
    "std::vector<std::vector<int>>",
    matrix_type_arguments,
    1,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor aliases_type_arg0_arg0{
    cjm::contract::type_kind::string,
    "std::string",
    "std::string",
    nullptr,
    0,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor aliases_type_arg0_arguments[] = {
    aliases_type_arg0_arg0,
};

inline constexpr cjm::contract::type_descriptor aliases_type_arg0{
    cjm::contract::type_kind::vector,
    "std::vector<std::string>",
    "std::vector<std::string>",
    aliases_type_arg0_arguments,
    1,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor aliases_type_arguments[] = {
    aliases_type_arg0,
};

inline constexpr cjm::contract::type_descriptor aliases_type{
    cjm::contract::type_kind::optional,
    "std::optional<std::vector<std::string>>",
    "std::optional<std::vector<std::string>>",
    aliases_type_arguments,
    1,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor buckets_type_arg0{
    cjm::contract::type_kind::string,
    "std::string",
    "std::string",
    nullptr,
    0,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor buckets_type_arg1_arg0{
    cjm::contract::type_kind::signed_integer,
    "int",
    "int",
    nullptr,
    0,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor buckets_type_arg1_arguments[] = {
    buckets_type_arg1_arg0,
};

inline constexpr cjm::contract::type_descriptor buckets_type_arg1{
    cjm::contract::type_kind::vector,
    "std::vector<int>",
    "std::vector<int>",
    buckets_type_arg1_arguments,
    1,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor buckets_type_arguments[] = {
    buckets_type_arg0,
    buckets_type_arg1,
};

inline constexpr cjm::contract::type_descriptor buckets_type{
    cjm::contract::type_kind::map,
    "std::map<std::string, std::vector<int>>",
    "std::map<std::string, std::vector<int>>",
    buckets_type_arguments,
    2,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor addresses_type_arg0{
    cjm::contract::type_kind::object,
    "company::contract_test::RecursiveAddress",
    "company::contract_test::RecursiveAddress",
    nullptr,
    0,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor addresses_type_arguments[] = {
    addresses_type_arg0,
};

inline constexpr cjm::contract::type_descriptor addresses_type{
    cjm::contract::type_kind::vector,
    "std::vector<company::contract_test::RecursiveAddress>",
    "std::vector<company::contract_test::RecursiveAddress>",
    addresses_type_arguments,
    1,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor maybe_address_type_arg0{
    cjm::contract::type_kind::object,
    "company::contract_test::RecursiveAddress",
    "company::contract_test::RecursiveAddress",
    nullptr,
    0,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor maybe_address_type_arguments[] = {
    maybe_address_type_arg0,
};

inline constexpr cjm::contract::type_descriptor maybe_address_type{
    cjm::contract::type_kind::optional,
    "std::optional<company::contract_test::RecursiveAddress>",
    "std::optional<company::contract_test::RecursiveAddress>",
    maybe_address_type_arguments,
    1,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor address_by_id_type_arg0{
    cjm::contract::type_kind::string,
    "std::string",
    "std::string",
    nullptr,
    0,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor address_by_id_type_arg1{
    cjm::contract::type_kind::object,
    "company::contract_test::RecursiveAddress",
    "company::contract_test::RecursiveAddress",
    nullptr,
    0,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor address_by_id_type_arguments[] = {
    address_by_id_type_arg0,
    address_by_id_type_arg1,
};

inline constexpr cjm::contract::type_descriptor address_by_id_type{
    cjm::contract::type_kind::map,
    "std::map<std::string, company::contract_test::RecursiveAddress>",
    "std::map<std::string, company::contract_test::RecursiveAddress>",
    address_by_id_type_arguments,
    2,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor address_groups_type_arg0_arg0{
    cjm::contract::type_kind::object,
    "company::contract_test::RecursiveAddress",
    "company::contract_test::RecursiveAddress",
    nullptr,
    0,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor address_groups_type_arg0_arguments[] = {
    address_groups_type_arg0_arg0,
};

inline constexpr cjm::contract::type_descriptor address_groups_type_arg0{
    cjm::contract::type_kind::vector,
    "std::vector<company::contract_test::RecursiveAddress>",
    "std::vector<company::contract_test::RecursiveAddress>",
    address_groups_type_arg0_arguments,
    1,
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor address_groups_type_arguments[] = {
    address_groups_type_arg0,
};

inline constexpr cjm::contract::type_descriptor address_groups_type{
    cjm::contract::type_kind::vector,
    "std::vector<std::vector<company::contract_test::RecursiveAddress>>",
    "std::vector<std::vector<company::contract_test::RecursiveAddress>>",
    address_groups_type_arguments,
    1,
    nullptr,
    0,
};

inline constexpr cjm::contract::field_descriptor fields[] = {
    {
        "matrix",
        "matrix",
        false,
        false,
        {"include/recursive_contract.hpp", 15, 35},
        &matrix_type,
    },
    {
        "aliases",
        "aliases",
        false,
        true,
        {"include/recursive_contract.hpp", 16, 45},
        &aliases_type,
    },
    {
        "buckets",
        "buckets",
        false,
        false,
        {"include/recursive_contract.hpp", 17, 51},
        &buckets_type,
    },
    {
        "addresses",
        "addresses",
        false,
        false,
        {"include/recursive_contract.hpp", 18, 43},
        &addresses_type,
    },
    {
        "maybe_address",
        "maybe_address",
        false,
        true,
        {"include/recursive_contract.hpp", 19, 49},
        &maybe_address_type,
    },
    {
        "address_by_id",
        "address_by_id",
        false,
        false,
        {"include/recursive_contract.hpp", 20, 57},
        &address_by_id_type,
    },
    {
        "address_groups",
        "address_groups",
        false,
        false,
        {"include/recursive_contract.hpp", 21, 56},
        &address_groups_type,
    },
};

} // namespace cjm::contract::generated_company_contract_test_RecursiveContract

template <>
struct cjm::contract::model_traits<company::contract_test::RecursiveContract> {
    static constexpr cjm::contract::model_descriptor model{
        "RecursiveContract",
        "company::contract_test::RecursiveContract",
        {"include/recursive_contract.hpp", 14, 8},
        cjm::contract::generated_company_contract_test_RecursiveContract::fields,
        7,
    };
};
