// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <nlohmann/json.hpp>

namespace company::model {

inline void to_json(nlohmann::json& j, const Address& value) {
    j["city"] = value.city;
}

inline void from_json(const nlohmann::json& j, Address& value) {
    j.at("city").get_to(value.city);
}

} // namespace company::model

namespace company::model {

inline void to_json(nlohmann::json& j, const RecursiveNlohmann& value) {
    j["matrix"] = value.matrix;
    if (value.aliases.has_value()) {
        j["aliases"] = *value.aliases;
    }
    j["buckets"] = value.buckets;
    j["sample_rows"] = value.sample_rows;
    j["addresses"] = value.addresses;
    if (value.maybe_address.has_value()) {
        j["maybe_address"] = *value.maybe_address;
    }
    j["address_by_id"] = value.address_by_id;
    j["address_groups"] = value.address_groups;
}

inline void from_json(const nlohmann::json& j, RecursiveNlohmann& value) {
    j.at("matrix").get_to(value.matrix);
    if (j.contains("aliases")) {
        value.aliases = j.at("aliases").get<std::vector<std::string>>();
    }
    j.at("buckets").get_to(value.buckets);
    j.at("sample_rows").get_to(value.sample_rows);
    j.at("addresses").get_to(value.addresses);
    if (j.contains("maybe_address")) {
        value.maybe_address = j.at("maybe_address").get<company::model::Address>();
    }
    j.at("address_by_id").get_to(value.address_by_id);
    j.at("address_groups").get_to(value.address_groups);
}

} // namespace company::model
