// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <simdjson.h>

#include <cstddef>
#include <cstdint>
#include <limits>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#ifndef CJM_SIMDJSON_RUNTIME_TYPES_DEFINED
#define CJM_SIMDJSON_RUNTIME_TYPES_DEFINED

namespace cjm::simdjson {

enum class DecodeErrorCode {
    none,
    syntax_error,
    expected_object,
    expected_bool,
    expected_integer,
    expected_unsigned_integer,
    integer_overflow,
    missing_required_field
};

enum class DecodePathSegmentKind {
    field,
    index
};

struct DecodePathSegment {
    DecodePathSegmentKind kind = DecodePathSegmentKind::field;
    std::string field_name;
    std::size_t index = 0;
};

struct DecodeError {
    DecodeErrorCode code = DecodeErrorCode::none;
    std::vector<DecodePathSegment> path;
    ::simdjson::error_code runtime_error = ::simdjson::SUCCESS;
};

template <typename T>
std::optional<T> from_json(
    std::string_view input,
    DecodeError& error);

} // namespace cjm::simdjson

#endif

namespace cjm::simdjson {

template <>
inline std::optional<::BoolValues>
from_json<::BoolValues>(
    std::string_view input,
    DecodeError& error) {
    // 1. Prepare the padded input owned for this decode.
    error = {};
    ::simdjson::padded_string padded_input(input);
    ::simdjson::ondemand::parser parser;

    // 2. Start one On-Demand document and read its root object.
    ::simdjson::ondemand::document document;
    auto runtime_error = parser.iterate(padded_input).get(document);
    if (runtime_error) {
        error.code = DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }

    ::simdjson::ondemand::object object;
    runtime_error = document.get_object().get(object);
    if (runtime_error) {
        error.code = runtime_error == ::simdjson::INCORRECT_TYPE
                         ? DecodeErrorCode::expected_object
                         : DecodeErrorCode::syntax_error;
        error.runtime_error = runtime_error;
        return std::nullopt;
    }

    // 3. Build a new object and track its required fields.
    ::BoolValues value{};
    bool has_enabled = false;

    // 4. Visit each JSON field once.
    for (auto field : object) {
        std::string_view key;
        runtime_error = field.unescaped_key().get(key);
        if (runtime_error) {
            error.code = DecodeErrorCode::syntax_error;
            error.runtime_error = runtime_error;
            return std::nullopt;
        }

        if (key == "enabled") {
            runtime_error = field.value().get_bool().get(value.enabled);
            if (runtime_error) {
                error.code = DecodeErrorCode::expected_bool;
                error.path.push_back(
                    {DecodePathSegmentKind::field, "enabled", 0});
                error.runtime_error = runtime_error;
                return std::nullopt;
            }
            has_enabled = true;
            continue;
        }
    }

    // 5. Verify that every required field was present.
    if (!has_enabled) {
        error.code = DecodeErrorCode::missing_required_field;
        error.path.push_back(
            {DecodePathSegmentKind::field, "enabled", 0});
        return std::nullopt;
    }

    // 6. Return the completely decoded object.
    return value;
}

} // namespace cjm::simdjson
