// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <nlohmann/json.hpp>

namespace company::model {

inline void to_json(nlohmann::json& j, const Detail& value) {
    j["source"] = value.source;
    j["shard"] = value.shard;
}

inline void from_json(const nlohmann::json& j, Detail& value) {
    j.at("source").get_to(value.source);
    j.at("shard").get_to(value.shard);
}

} // namespace company::model

namespace company::model {

inline void to_json(nlohmann::json& j, const Event& value) {
    j["sequence"] = value.sequence;
    j["timestamp_ns"] = value.timestamp_ns;
    j["status"] = value.status;
    j["detail"] = value.detail;
    j["tags"] = value.tags;
    j["buckets"] = value.buckets;
    if (value.retry_after.has_value()) {
        j["retry_after"] = *value.retry_after;
    }
    if (value.attributes.has_value()) {
        j["attributes"] = *value.attributes;
    }
}

inline void from_json(const nlohmann::json& j, Event& value) {
    j.at("sequence").get_to(value.sequence);
    j.at("timestamp_ns").get_to(value.timestamp_ns);
    j.at("status").get_to(value.status);
    j.at("detail").get_to(value.detail);
    j.at("tags").get_to(value.tags);
    j.at("buckets").get_to(value.buckets);
    if (j.contains("retry_after")) {
        value.retry_after = j.at("retry_after").get<std::uint64_t>();
    }
    if (j.contains("attributes")) {
        value.attributes = j.at("attributes").get<std::unordered_map<std::string, std::string>>();
    }
}

} // namespace company::model
