// This file was generated by CJM.
// Do not edit this file manually.

#pragma once

#include <nlohmann/json.hpp>
#include <cjm/model_contract.hpp>

namespace company::model {

inline void to_json(nlohmann::json& j, const Detail& value) {
    j["source"] = value.source;
    j["shard"] = value.shard;
}

inline void from_json(const nlohmann::json& j, Detail& value) {
    j.at("source").get_to(value.source);
    j.at("shard").get_to(value.shard);
}

} // namespace company::model

namespace cjm::contract::generated_company_model_Detail {

inline constexpr cjm::contract::type_descriptor source_type{
    cjm::contract::type_kind::string,
    "std::string",
    "std::string",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor shard_type{
    cjm::contract::type_kind::unsigned_integer,
    "std::uint32_t",
    "std::uint32_t",
    nullptr,
    0,
};

} // namespace cjm::contract::generated_company_model_Detail

namespace company::model {

inline void to_json(nlohmann::json& j, const Event& value) {
    j["sequence"] = value.sequence;
    j["timestamp_ns"] = value.timestamp_ns;
    j["status"] = value.status;
    j["detail"] = value.detail;
    j["tags"] = value.tags;
    j["buckets"] = value.buckets;
    if (value.retry_after.has_value()) {
        j["retry_after"] = *value.retry_after;
    }
    if (value.attributes.has_value()) {
        j["attributes"] = *value.attributes;
    }
}

inline void from_json(const nlohmann::json& j, Event& value) {
    j.at("sequence").get_to(value.sequence);
    j.at("timestamp_ns").get_to(value.timestamp_ns);
    j.at("status").get_to(value.status);
    j.at("detail").get_to(value.detail);
    j.at("tags").get_to(value.tags);
    j.at("buckets").get_to(value.buckets);
    if (j.contains("retry_after")) {
        value.retry_after = j.at("retry_after").get<std::uint64_t>();
    }
    if (j.contains("attributes")) {
        value.attributes = j.at("attributes").get<std::unordered_map<std::string, std::string>>();
    }
}

} // namespace company::model

namespace cjm::contract::generated_company_model_Event {

inline constexpr cjm::contract::type_descriptor sequence_type{
    cjm::contract::type_kind::unsigned_integer,
    "std::uint64_t",
    "std::uint64_t",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor timestamp_ns_type{
    cjm::contract::type_kind::signed_integer,
    "std::int64_t",
    "std::int64_t",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor status_type{
    cjm::contract::type_kind::enum_,
    "company::model::Status",
    "company::model::Status",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor detail_type{
    cjm::contract::type_kind::object,
    "company::model::Detail",
    "company::model::Detail",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor tags_type{
    cjm::contract::type_kind::vector,
    "std::vector<std::string>",
    "std::vector<std::string>",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor buckets_type{
    cjm::contract::type_kind::map,
    "std::map<std::string, std::vector<std::uint64_t>>",
    "std::map<std::string, std::vector<std::uint64_t>>",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor retry_after_type{
    cjm::contract::type_kind::optional,
    "std::optional<std::uint64_t>",
    "std::optional<std::uint64_t>",
    nullptr,
    0,
};

inline constexpr cjm::contract::type_descriptor attributes_type{
    cjm::contract::type_kind::optional,
    "std::optional<std::unordered_map<std::string, std::string>>",
    "std::optional<std::unordered_map<std::string, std::string>>",
    nullptr,
    0,
};

} // namespace cjm::contract::generated_company_model_Event
