#include "backends/schema/schema_generator.hpp"

#include <sstream>
#include <string>

namespace cjm::generator::schema {

void generate_schema_fragment(std::ostringstream& out,
                              const metadata::FieldType& type,
                              const metadata::ProjectModel& project);
/**
 * Return the JSON schema primitive type name for a scalar Metadata IR type.
 *
 * This helper only handles scalar/string mappings. Container and object
 * mappings are generated by generated_type_schema.
 */
std::string schema_type_name(metadata::FieldTypeKind kind) {
    switch (kind) {
    case metadata::FieldTypeKind::Bool:
        return "boolean";
    case metadata::FieldTypeKind::SignedInteger:
    case metadata::FieldTypeKind::UnsignedInteger:
        return "integer";
    case metadata::FieldTypeKind::FloatingPoint:
        return "number";
    case metadata::FieldTypeKind::String:
        return "string";
    default:
        return "object";
    }
}

/**
 * Return whether this Metadata IR type is a scalar/string schema mapping.
 *
 * This function only recognizes leaf JSON Schema mappings. Container mappings
 * are handled by is_supported_schema_type().
 */
bool is_supported_simple_schema_type(const metadata::FieldType& type) {
    return type.kind == metadata::FieldTypeKind::Bool ||
           type.kind == metadata::FieldTypeKind::SignedInteger ||
           type.kind == metadata::FieldTypeKind::UnsignedInteger ||
           type.kind == metadata::FieldTypeKind::FloatingPoint ||
           type.kind == metadata::FieldTypeKind::String;
}

// Find the enum model for an enum field type.
const metadata::EnumModel*
find_enum_model(const std::vector<metadata::EnumModel>& enums,
                const metadata::FieldType& type) {
    for (const auto& enum_model : enums) {
        if (enum_model.qualified_name == type.qualified_name) {
            return &enum_model;
        }
    }
    return nullptr;
}

// Find the type model for a user-defined field type.
const metadata::TypeModel*
find_type_model(const std::vector<metadata::TypeModel>& types,
                const metadata::FieldType& type) {
    for (const auto& type_model : types) {
        if (type.qualified_name == type_model.qualified_name) {
            return &type_model;
        }
    }
    return nullptr;
}

// Return whether an enum field has schema values available.
bool is_supported_enum_schema_type(
    const metadata::FieldType& type,
    const std::vector<metadata::EnumModel>& enums) {
    if (type.kind != metadata::FieldTypeKind::Enum) {
        return false;
    }
    const auto* enum_model = find_enum_model(enums, type);
    if (enum_model == nullptr) {
        return false;
    }
    if (enum_model->enumerators.size() == 0) {
        return false;
    }
    return true;
}

/**
 * Return whether the schema backend can emit a schema fragment for this
 * Metadata IR type.
 */
bool is_supported_schema_type(const metadata::FieldType& type,
                              const metadata::ProjectModel& project) {
    if (is_supported_simple_schema_type(type)) {
        return true;
    }

    if (type.kind == metadata::FieldTypeKind::Vector ||
        type.kind == metadata::FieldTypeKind::Array) {
        return type.arguments.size() == 1 &&
               is_supported_schema_type(type.arguments[0], project);
    }
    if (type.kind == metadata::FieldTypeKind::Optional) {
        return type.arguments.size() == 1 &&
               is_supported_schema_type(type.arguments[0], project);
    }
    if (type.kind == metadata::FieldTypeKind::Map) {
        return type.arguments.size() == 2 &&
               type.arguments[0].kind == metadata::FieldTypeKind::String &&
               is_supported_schema_type(type.arguments[1], project);
    }
    if (type.kind == metadata::FieldTypeKind::Enum) {
        return is_supported_enum_schema_type(type, project.enums);
    }
    if (type.kind == metadata::FieldTypeKind::UserDefined) {
        return find_type_model(project.types, type) != nullptr;
    }
    return false;
}

// Return whether a field should be listed in the schema required array.
bool is_required_schema_field(const metadata::FieldModel& field,
                              const metadata::ProjectModel& project) {
    if (field.json.ignored) {
        return false;
    }
    if (!is_supported_schema_type(field.type, project)) {
        return false;
    }
    if (field.type.kind == metadata::FieldTypeKind::Optional) {
        return false;
    }
    return true;
}

// Generate a nullable JSON Schema fragment for one optional field type.
void generate_optional_schema_fragment(std::ostringstream& out,
                                       const metadata::FieldType& type,
                                       const metadata::ProjectModel& project) {
    if (type.arguments.size() == 0) {
        return;
    }
    out << "{ \"anyOf\": [";
    generate_schema_fragment(out, type.arguments[0], project);
    out << ", { \"type\": \"null\" }] }";
}

// Generate a JSON Schema object fragment for a string-keyed map field.
void generate_map_schema_fragment(std::ostringstream& out,
                                  const metadata::FieldType& type,
                                  const metadata::ProjectModel& project) {
    if (type.arguments.size() != 2) {
        return;
    }
    if (type.arguments[0].kind != metadata::FieldTypeKind::String) {
        return;
    }
    out << "{ \"type\": \"object\", \"additionalProperties\": ";
    generate_schema_fragment(out, type.arguments[1], project);
    out << " }";
}

// Generate the JSON Schema fragment for an enum string field.
void generate_enum_schema_fragment(std::ostringstream& out,
                                   const metadata::EnumModel& enum_model) {
    out << "{ \"type\": \"string\", \"enum\": [";
    bool not_first_element = false;
    for (const auto& enumerator : enum_model.enumerators) {
        if (not_first_element) {
            out << ", ";
        }
        out << "\"" << enumerator << "\"";
        not_first_element = true;
    }
    out << "] }";
}

// Generate the JSON Schema fragment for a user-defined object field.
void generate_object_ref_schema_fragment(std::ostringstream& out,
                                         const metadata::TypeModel& type) {
    out << "{ \"$ref\": \"#/$defs/" << type.name << "\" }";
}

// Generate the JSON Schema fragment for one supported Metadata IR field type.
void generate_schema_fragment(std::ostringstream& out,
                              const metadata::FieldType& type,
                              const metadata::ProjectModel& project) {
    if (is_supported_simple_schema_type(type)) {
        out << "{ \"type\": \"" << schema_type_name(type.kind) << "\" }";
        return;
    }

    if (type.kind == metadata::FieldTypeKind::Vector) {
        if (type.arguments.size() != 1) {
            return;
        }
        out << "{ \"type\": \"array\", \"items\": ";

        generate_schema_fragment(out, type.arguments[0], project);
        out << " }";

        return;
    }

    if (type.kind == metadata::FieldTypeKind::Array) {
        if (type.arguments.size() != 1) {
            return;
        }
        out << "{ \"type\": \"array\", \"items\": ";
        generate_schema_fragment(out, type.arguments[0], project);
        out << ", \"minItems\": " << type.array_extent
            << ", \"maxItems\": " << type.array_extent << " }";
        return;
    }

    if (type.kind == metadata::FieldTypeKind::Optional) {
        generate_optional_schema_fragment(out, type, project);
        return;
    }
    if (type.kind == metadata::FieldTypeKind::Map) {
        generate_map_schema_fragment(out, type, project);
        return;
    }
    if (type.kind == metadata::FieldTypeKind::Enum) {
        const auto& enum_model = find_enum_model(project.enums, type);
        generate_enum_schema_fragment(out, *enum_model);
        return;
    }
    if (type.kind == metadata::FieldTypeKind::UserDefined) {
        const auto& object_model = find_type_model(project.types, type);
        generate_object_ref_schema_fragment(out, *object_model);
        return;
    }
}

void generate_field_schema(std::ostringstream& out,
                           const metadata::FieldModel& field,
                           const std::string& indent,
                           const metadata::ProjectModel& project) {
    out << indent << "\"" << field.json.name << "\": ";
    generate_schema_fragment(out, field.type, project);
}

// Generate a JSON Schema definition for one referenced object type.
void generate_object_definition(std::ostringstream& out,
                                const metadata::TypeModel& type,
                                const metadata::ProjectModel& project) {
    out << "    \"" << type.name << "\": {\n"
        << "      \"type\": \"object\",\n"
        << "      \"properties\": {\n";
    bool wrote_property = false;
    for (const auto& field : type.fields) {
        if (field.json.ignored) {
            continue;
        }
        if (!is_supported_schema_type(field.type, project)) {
            continue;
        }
        if (wrote_property) {
            out << ",\n";
        }
        generate_field_schema(out, field, "        ", project);
        wrote_property = true;
    }
    out << "\n"
        << "      },\n"
        << "      \"required\": [";

    bool wrote_required = false;
    for (const auto& field : type.fields) {
        if (!is_required_schema_field(field, project)) {
            continue;
        }
        if (wrote_required) {
            out << ", ";
        }
        out << "\"" << field.json.name << "\"";
        wrote_required = true;
    }
    out << "]\n"
        << "    }";
}

void generate_type_schema(std::ostringstream& out,
                          const metadata::TypeModel& type,
                          const metadata::ProjectModel& project) {
    out << "{\n"
        << "  \"$schema\": "
           "\"https://json-schema.org/draft/2020-12/schema\",\n"
        << "  \"title\": \"" << type.name << "\",\n"
        << "  \"type\": \"object\",\n"
        << "  \"properties\": {\n";

    bool wrote_property = false;
    for (const auto& field : type.fields) {
        if (field.json.ignored) {
            continue;
        }
        if (!is_supported_schema_type(field.type, project)) {
            continue;
        }
        if (wrote_property) {
            out << ",\n";
        }
        generate_field_schema(out, field, "    ", project);
        wrote_property = true;
    }

    out << "\n"
        << "  },\n"
        << "  \"required\": [";

    bool wrote_required = false;
    for (const auto& field : type.fields) {
        if (!is_required_schema_field(field, project)) {
            continue;
        }
        if (wrote_required) {
            out << ", ";
        }
        out << "\"" << field.json.name << "\"";
        wrote_required = true;
    }
    out << "]";

    if (project.types.size() > 1) {
        out << ",\n"
            << "  \"$defs\": {\n";
        bool wrote_definition = false;
        for (uint32_t i = 1; i < project.types.size(); ++i) {
            if (wrote_definition) {
                out << ",\n";
            }
            generate_object_definition(out, project.types[i], project);
            wrote_definition = true;
        }
        out << "\n"
            << "  }";
    }
    out << "\n"
        << "}\n";
}

std::string generate_schema(const metadata::ProjectModel& project) {
    std::ostringstream out;
    if (!project.types.empty()) {
        generate_type_schema(out, project.types.front(), project);
    }
    return out.str();
}

} // namespace cjm::generator::schema
