#include "backends/schema/schema_generator.hpp"

#include <sstream>
#include <string>

namespace cjm::generator::schema {

void generate_schema_fragment(
    std::ostringstream& out, const metadata::FieldType& type,
    const std::vector<metadata::EnumModel>& enums = {});
/**
 * Return the JSON schema primitive type name for a scalar Metadata IR type.
 *
 * This helper only handles scalar/string mappings. Container and object
 * mappings are generated by generated_type_schema.
 */
std::string schema_type_name(metadata::FieldTypeKind kind) {
    switch (kind) {
    case metadata::FieldTypeKind::Bool:
        return "boolean";
    case metadata::FieldTypeKind::SignedInteger:
    case metadata::FieldTypeKind::UnsignedInteger:
        return "integer";
    case metadata::FieldTypeKind::FloatingPoint:
        return "number";
    case metadata::FieldTypeKind::String:
        return "string";
    default:
        return "object";
    }
}

/**
 * Return whether this Metadata IR type is a scalar/string schema mapping.
 *
 * This function only recognizes leaf JSON Schema mappings. Container mappings
 * are handled by is_supported_schema_type().
 */
bool is_supported_simple_schema_type(const metadata::FieldType& type) {
    return type.kind == metadata::FieldTypeKind::Bool ||
           type.kind == metadata::FieldTypeKind::SignedInteger ||
           type.kind == metadata::FieldTypeKind::UnsignedInteger ||
           type.kind == metadata::FieldTypeKind::FloatingPoint ||
           type.kind == metadata::FieldTypeKind::String;
}

// Find the enum model for an enum field type.
const metadata::EnumModel*
find_enum_model(const std::vector<metadata::EnumModel>& enums,
                const metadata::FieldType& type) {
    for (const auto& enum_model : enums) {
        if (enum_model.qualified_name == type.qualified_name) {
            return &enum_model;
        }
    }
    return nullptr;
}

// Return whether an enum field has schema values available.
bool is_supported_enum_schema_type(
    const metadata::FieldType& type,
    const std::vector<metadata::EnumModel>& enums) {
    if (type.kind != metadata::FieldTypeKind::Enum) {
        return false;
    }
    const auto* enum_model = find_enum_model(enums, type);
    if (enum_model == nullptr) {
        return false;
    }
    if (enum_model->enumerators.size() == 0) {
        return false;
    }
    return true;
}

/**
 * Return whether the schema backend can emit a schema for this validated field
 * type in the current v0.5 slice.
 *
 * This is backend capability gating. It does not validate C++ syntax or decide
 * whether the field type is semantically supported by CJM.
 */
bool is_supported_schema_type(const metadata::FieldType& type,
                              const std::vector<metadata::EnumModel>& enums) {
    if (is_supported_simple_schema_type(type)) {
        return true;
    }

    if (type.kind == metadata::FieldTypeKind::Vector ||
        type.kind == metadata::FieldTypeKind::Array) {
        if (type.arguments.size() == 1 &&
            is_supported_simple_schema_type(type.arguments[0])) {
            return true;
        }
    }
    if (type.kind == metadata::FieldTypeKind::Optional) {
        return type.arguments.size() == 1 &&
               is_supported_simple_schema_type(type.arguments[0]);
    }
    if (type.kind == metadata::FieldTypeKind::Map) {
        return type.arguments.size() == 2 &&
               type.arguments[0].kind == metadata::FieldTypeKind::String &&
               is_supported_simple_schema_type(type.arguments[1]);
    }
    if (type.kind == metadata::FieldTypeKind::Enum) {
        return is_supported_enum_schema_type(type, enums);
    }
    return false;
}

// Return whether a field should be listed in the schema required array.
bool is_required_schema_field(const metadata::FieldModel& field,
                              const std::vector<metadata::EnumModel>& enums) {
    if (field.json.name.empty()) {
        return false;
    }
    if (!is_supported_schema_type(field.type, enums)) {
        return false;
    }
    if (field.type.kind == metadata::FieldTypeKind::Optional) {
        return false;
    }
    return true;
}

// Generate the JSON Schema type array for an optional simple field type.
void generate_optional_schema_fragment(std::ostringstream& out,
                                       const metadata::FieldType& type) {
    if (type.arguments.size() == 0) {
        return;
    }
    const auto& kind = type.arguments[0].kind;
    if (kind == metadata::FieldTypeKind::Bool) {
        out << "{ \"type\": [\"boolean\", \"null\"] }";
        return;
    }
    if (kind == metadata::FieldTypeKind::SignedInteger) {
        out << "{ \"type\": [\"integer\", \"null\"] }";
        return;
    }
    if (kind == metadata::FieldTypeKind::UnsignedInteger) {
        out << "{ \"type\": [\"integer\", \"null\"], \"minimum\": 0 }";
        return;
    }
    if (kind == metadata::FieldTypeKind::FloatingPoint) {
        out << "{ \"type\": [\"number\", \"null\"] }";
        return;
    }
    if (kind == metadata::FieldTypeKind::String) {
        out << "{ \"type\": [\"string\", \"null\"] }";
        return;
    }
}

// Generate the JSON Schema fragment for a string-keyed map field.
void generate_map_schema_fragment(std::ostringstream& out,
                                  const metadata::FieldType& type) {
    if (type.arguments.size() != 2) {
        return;
    }
    if (!is_supported_simple_schema_type(type.arguments[0]) ||
        (!is_supported_simple_schema_type(type.arguments[1]))) {
        return;
    }
    const auto& val_kind = type.arguments[1].kind;
    out << "{ \"type\": \"object\", \"additionalProperties\": ";
    generate_schema_fragment(out, type.arguments[1]);
    out << " }";
}

// Generate the JSON Schema fragment for an enum string field.
void generate_enum_schema_fragment(std::ostringstream& out,
                                   const metadata::EnumModel& enum_model) {
    out << "{ \"type\": \"string\", \"enum\": [";
    bool not_first_element = false;
    for (const auto& enumerator : enum_model.enumerators) {
        if (not_first_element) {
            out << ", ";
        }
        out << "\"" << enumerator << "\"";
        not_first_element = true;
    }
    out << "] }";
}
/**
 * Generate the JSON Schema fragment for one validated field type.
 *
 * Inputs:
 *     type - Metadata IR field type already validated by Semantic Analysis.
 *
 * Output:
 *     Writes a JSON Schema object fragment such `{"type": "string"}` or
 *     `{"type": "array", "items": { "type": "integer" } }`.
 *
 * This function maps IR facts to schema output. It must not parse C++ type
 * spellings or inspect parser-specific data.
 */
void generate_schema_fragment(std::ostringstream& out,
                              const metadata::FieldType& type,
                              const std::vector<metadata::EnumModel>& enums) {
    if (is_supported_simple_schema_type(type)) {
        out << "{ \"type\": \"" << schema_type_name(type.kind) << "\" }";
        return;
    }

    if (type.kind == metadata::FieldTypeKind::Vector) {
        out << "{ \"type\": \"array\", \"items\": ";

        for (const auto& arg : type.arguments) {
            generate_schema_fragment(out, arg);
        }
        out << " }";

        return;
    }

    if (type.kind == metadata::FieldTypeKind::Array) {
        out << "{ \"type\": \"array\", \"items\": ";
        for (const auto& arg : type.arguments) {
            generate_schema_fragment(out, arg);
        }
        out << ", \"minItems\": " << type.array_extent
            << ", \"maxItems\": " << type.array_extent << " }";
        return;
    }

    if (type.kind == metadata::FieldTypeKind::Optional) {
        generate_optional_schema_fragment(out, type);
        return;
    }
    if (type.kind == metadata::FieldTypeKind::Map) {
        generate_map_schema_fragment(out, type);
        return;
    }
    if (type.kind == metadata::FieldTypeKind::Enum) {
        const auto& enum_model = find_enum_model(enums, type);
        generate_enum_schema_fragment(out, *enum_model);
        return;
    }
}

void generate_field_schema(std::ostringstream& out,
                           const metadata::FieldModel& field,
                           const std::string& indent,
                           const std::vector<metadata::EnumModel>& enums) {
    out << indent << "\"" << field.json.name << "\": ";
    generate_schema_fragment(out, field.type, enums);
}

void generate_type_schema(std::ostringstream& out,
                          const metadata::TypeModel& type,
                          const std::vector<metadata::EnumModel>& enums) {
    out << "{\n"
        << "  \"$schema\": "
           "\"https://json-schema.org/draft/2020-12/schema\",\n"
        << "  \"title\": \"" << type.name << "\",\n"
        << "  \"type\": \"object\",\n"
        << "  \"properties\": {\n";

    bool wrote_property = false;
    for (const auto& field : type.fields) {
        if (field.json.name.empty()) {
            continue;
        }
        if (!is_supported_schema_type(field.type, enums)) {
            continue;
        }
        if (wrote_property) {
            out << ",\n";
        }
        generate_field_schema(out, field, "    ", enums);
        wrote_property = true;
    }

    out << "\n"
        << "  },\n"
        << "  \"required\": [";

    bool wrote_required = false;
    for (const auto& field : type.fields) {
        if (!is_required_schema_field(field, enums)) {
            continue;
        }
        if (wrote_required) {
            out << ", ";
        }
        out << "\"" << field.json.name << "\"";
        wrote_required = true;
    }
    out << "]\n"
        << "}\n";
}

std::string generate_schema(const metadata::ProjectModel& project) {
    std::ostringstream out;
    if (!project.types.empty()) {
        generate_type_schema(out, project.types.front(), project.enums);
    }
    return out.str();
}

} // namespace cjm::generator::schema
