#include "backends/schema/schema_generator.hpp"

#include <sstream>
#include <string>

namespace cjm::generator::schema {

/**
 * Return the JSON schema primitive type name for a scalar Metadata IR type.
 *
 * This helper only handles scalar/string mappings. Container and object
 * mappings are generated by generated_type_schema.
 */
std::string schema_type_name(metadata::FieldTypeKind kind) {
    switch (kind) {
    case metadata::FieldTypeKind::Bool:
        return "boolean";
    case metadata::FieldTypeKind::SignedInteger:
    case metadata::FieldTypeKind::UnsignedInteger:
        return "integer";
    case metadata::FieldTypeKind::FloatingPoint:
        return "number";
    case metadata::FieldTypeKind::String:
        return "string";
    default:
        return "object";
    }
}

/**
 * Return whether this Metadata IR type is a scalar/string schema mapping.
 *
 * This function only recognizes leaf JSON Schema mappings. Container mappings
 * are handled by is_supported_schema_type().
 */
bool is_supported_simple_schema_type(const metadata::FieldType& type) {
    return type.kind == metadata::FieldTypeKind::Bool ||
           type.kind == metadata::FieldTypeKind::SignedInteger ||
           type.kind == metadata::FieldTypeKind::UnsignedInteger ||
           type.kind == metadata::FieldTypeKind::FloatingPoint ||
           type.kind == metadata::FieldTypeKind::String;
}

/**
 * Return whether the schema backend can emit a schema for this validated field
 * type in the current v0.5 slice.
 *
 * This is backend capability gating. It does not validate C++ syntax or decide
 * whether the field type is semantically supported by CJM.
 */
bool is_supported_schema_type(const metadata::FieldType& type) {
    if (is_supported_simple_schema_type(type)) {
        return true;
    }

    if (type.kind == metadata::FieldTypeKind::Vector ||
        type.kind == metadata::FieldTypeKind::Array) {
        if (type.arguments.size() == 1 &&
            is_supported_simple_schema_type(type.arguments[0])) {
            return true;
        }
    }
    return false;
}

/**
 * Generate the JSON Schema fragment for one validated field type.
 *
 * Inputs:
 *     type - Metadata IR field type already validated by Semantic Analysis.
 *
 * Output:
 *     Writes a JSON Schema object fragment such `{"type": "string"}` or
 *     `{"type": "array", "items": { "type": "integer" } }`.
 *
 * This function maps IR facts to schema output. It must not parse C++ type
 * spellings or inspect parser-specific data.
 */
void generate_schema_fragment(std::ostringstream& out,
                              const metadata::FieldType& type) {
    if (is_supported_simple_schema_type(type)) {
        out << "{ \"type\": \"" << schema_type_name(type.kind) << "\" }";
        return;
    }

    if (type.kind == metadata::FieldTypeKind::Vector) {
        out << "{ \"type\": \"array\", \"items\": ";

        for (const auto& arg : type.arguments) {
            generate_schema_fragment(out, arg);
        }
        out << " }";

        return;
    }

    if (type.kind == metadata::FieldTypeKind::Array) {
        out << "{ \"type\": \"array\", \"items\": ";
        for (const auto& arg : type.arguments) {
            generate_schema_fragment(out, arg);
        }
        out << ", \"minItems\": " << type.array_extent
            << ", \"maxItems\": " << type.array_extent << " }";
        return;
    }
}

void generate_field_schema(std::ostringstream& out,
                           const metadata::FieldModel& field,
                           const std::string& indent) {
    out << indent << "\"" << field.json.name << "\": ";
    generate_schema_fragment(out, field.type);
}

void generate_type_schema(std::ostringstream& out,
                          const metadata::TypeModel& type) {
    out << "{\n"
        << "  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n"
        << "  \"title\": \"" << type.name << "\",\n"
        << "  \"type\": \"object\",\n"
        << "  \"properties\": {\n";

    bool wrote_property = false;
    for (const auto& field : type.fields) {
        if (field.json.name.empty()) {
            continue;
        }
        if (!is_supported_schema_type(field.type)) {
            continue;
        }
        if (wrote_property) {
            out << ",\n";
        }
        generate_field_schema(out, field, "    ");
        wrote_property = true;
    }

    out << "\n"
        << "  },\n"
        << "  \"required\": [";

    bool wrote_required = false;
    for (const auto& field : type.fields) {
        if (field.json.name.empty() || !is_supported_schema_type(field.type)) {
            continue;
        }
        if (wrote_required) {
            out << ", ";
        }
        out << "\"" << field.json.name << "\"";
        wrote_required = true;
    }
    out << "]\n"
        << "}\n";
}

std::string generate_schema(const metadata::ProjectModel& project) {
    std::ostringstream out;
    if (!project.types.empty()) {
        generate_type_schema(out, project.types.front());
    }
    return out.str();
}

} // namespace cjm::generator::schema
