#include "generator/cpp_generator.hpp"

#include <sstream>

namespace cjm::generator {

void generate_to_json(std::ostringstream& out,
                      const metadata::TypeModel& type) {
    out << "inline void to_json(nlohmann::json& j, const "
        << type.qualified_name << "& value) {\n";
    for (const auto& field : type.fields) {
        out << "    j[\"" << field.json.name << "\"] = value." << field.name
            << ";\n";
    }
    out << "}\n";
}

void generate_from_json(std::ostringstream& out,
                        const metadata::TypeModel& type) {

    out << "inline void from_json(const nlohmann::json& j, "
        << type.qualified_name << "& value) {\n";

    for (const auto& field : type.fields) {
        out << "   j.at(\"" << field.json.name << "\").get_to(value."
            << field.name << ");\n";
    }
    out << "}\n";
}

std::string generate_header(const metadata::ProjectModel& project) {

    std::ostringstream out;

    out << "// This file was generated by CJM.\n"
        << "// Do not edit this file manually.\n"
        << "\n"
        << "#pragma once\n"
        << "\n"
        << "#include <nlohmann/json.hpp>\n";

    out << "\n";

    for (const auto& type : project.types) {
        generate_to_json(out, type);
        out << "\n";
    }

    return out.str();
}

} // namespace cjm::generator
