#include "generator/cpp_generator.hpp"

#include <sstream>

namespace cjm::generator {

std::string generate_header(const metadata::ProjectModel &project) {
    (void)project;

    std::ostringstream out;

    out << "// This file was generated by CJM.\n"
        << "// Do not edit this file manually.\n"
        << "\n"
        << "#pragma once\n"
        << "\n"
        << "#include <nlohmann/json.hpp>\n";

    return out.str();
}

} // namespace cjm::generator
