#include "backends/nlohmann/cpp_generator.hpp"

#include <cstddef>
#include <sstream>
#include <vector>

namespace cjm::generator {

void open_namespace(std::ostringstream& out,
                    const std::vector<std::string>& namespace_path) {

    if (namespace_path.empty()) {
        return;
    }

    out << "namespace ";
    for (std::size_t i = 0; i < namespace_path.size(); ++i) {
        if (i > 0) {
            out << "::";
        }
        out << namespace_path[i];
    }
    out << " {\n\n";
}

void close_namespace(std::ostringstream& out,
                     const std::vector<std::string>& namespace_path) {
    if (namespace_path.empty()) {
        return;
    }

    out << "} // namespace ";
    for (std::size_t i = 0; i < namespace_path.size(); ++i) {
        if (i > 0) {
            out << "::";
        }
        out << namespace_path[i];
    }
    out << "\n";
}

// Generate one to_json assignment from a validated Metadata IR field.
void generate_to_json_field(std::ostringstream& out,
                            const metadata::FieldModel& field) {
    if (!field.json.name.empty()) {
        out << "    j[\"" << field.json.name << "\"] = value." << field.name
            << ";\n";
    }
}

// Generate one from_json assignment from a validated Metadata IR field.
void generate_from_json_field(std::ostringstream& out,
                              const metadata::FieldModel& field) {
    if (!field.json.name.empty()) {
        out << "    j.at(\"" << field.json.name << "\").get_to(value."
            << field.name << ");\n";
    }
}

void generate_to_json(std::ostringstream& out,
                      const metadata::TypeModel& type) {
    out << "inline void to_json(nlohmann::json& j, const " << type.name
        << "& value) {\n";
    for (const auto& field : type.fields) {
        generate_to_json_field(out, field);
    }
    out << "}\n";
}

void generate_from_json(std::ostringstream& out,
                        const metadata::TypeModel& type) {

    out << "inline void from_json(const nlohmann::json& j, " << type.name
        << "& value) {\n";

    for (const auto& field : type.fields) {
        generate_from_json_field(out, field);
    }
    out << "}\n";
}

std::string generate_header(const metadata::ProjectModel& project) {

    std::ostringstream out;

    out << "// This file was generated by CJM.\n"
        << "// Do not edit this file manually.\n"
        << "\n"
        << "#pragma once\n"
        << "\n"
        << "#include <nlohmann/json.hpp>\n";

    out << "\n";

    for (std::size_t i = 0; i < project.types.size(); ++i) {
        const auto& type = project.types[i];

        open_namespace(out, type.namespace_path);
        generate_to_json(out, type);
        out << "\n";
        generate_from_json(out, type);
        out << "\n";
        close_namespace(out, type.namespace_path);

        if (i + 1 < project.types.size()) {
            out << "\n";
        }
    }

    return out.str();
}

} // namespace cjm::generator
