#include "backends/simdjson/cpp_generator.hpp"

#include <sstream>
#include <string>

namespace cjm::generator::simdjson {
namespace {

// Return whether a Metadata IR kind is supported by the initial decode spike.
bool is_supported_scalar_kind(metadata::FieldTypeKind kind) {
    switch (kind) {
    case metadata::FieldTypeKind::Bool:
    case metadata::FieldTypeKind::SignedInteger:
    case metadata::FieldTypeKind::UnsignedInteger:
    case metadata::FieldTypeKind::FloatingPoint:
    case metadata::FieldTypeKind::String:
        return true;
    case metadata::FieldTypeKind::Enum:
    case metadata::FieldTypeKind::Array:
    case metadata::FieldTypeKind::Vector:
    case metadata::FieldTypeKind::Map:
    case metadata::FieldTypeKind::Optional:
    case metadata::FieldTypeKind::UserDefined:
        return false;
    }
    return false;
}

// Return the first unsupported-field diagnostic, or an empty string.
std::string validate_project(const metadata::ProjectModel& project) {
    for (const auto& type : project.types) {
        for (const auto& field : type.fields) {
            if (field.json.ignored) {
                continue;
            }
            if (is_supported_scalar_kind(field.type.kind)) {
                continue;
            }

            const auto& type_name = field.type.spelling.empty()
                                        ? field.type.qualified_name
                                        : field.type.spelling;

            return "simdjson backend does not support field '" + field.name +
                   "' of type " + type_name;
        }
    }
    return {};
}

} // namespace

GenerationResult generate_header(const metadata::ProjectModel& project) {
    const auto error = validate_project(project);
    if (!error.empty()) {
        return GenerationResult{false, {}, error};
    }

    std::ostringstream header;
    header << "// This file was generated by CJM.\n"
           << "// Do not edit this file manually.\n"
           << "\n"
           << "#pragma once\n"
           << "\n"
           << "#include <simdjson.h>\n";

    return GenerationResult{true, header.str(), {}};
}

} // namespace cjm::generator::simdjson
